# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dddong/workspace/ClionProjects/miniSqlFrom0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dddong/workspace/ClionProjects/miniSqlFrom0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dddong/workspace/ClionProjects/miniSqlFrom0/CMakeFiles /Users/dddong/workspace/ClionProjects/miniSqlFrom0/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dddong/workspace/ClionProjects/miniSqlFrom0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named miniSqlFrom0

# Build rule for target.
miniSqlFrom0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 miniSqlFrom0
.PHONY : miniSqlFrom0

# fast build rule for target.
miniSqlFrom0/fast:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/build
.PHONY : miniSqlFrom0/fast

BM/bm_buffermgr.o: BM/bm_buffermgr.cpp.o

.PHONY : BM/bm_buffermgr.o

# target to build an object file
BM/bm_buffermgr.cpp.o:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/BM/bm_buffermgr.cpp.o
.PHONY : BM/bm_buffermgr.cpp.o

BM/bm_buffermgr.i: BM/bm_buffermgr.cpp.i

.PHONY : BM/bm_buffermgr.i

# target to preprocess a source file
BM/bm_buffermgr.cpp.i:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/BM/bm_buffermgr.cpp.i
.PHONY : BM/bm_buffermgr.cpp.i

BM/bm_buffermgr.s: BM/bm_buffermgr.cpp.s

.PHONY : BM/bm_buffermgr.s

# target to generate assembly for a file
BM/bm_buffermgr.cpp.s:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/BM/bm_buffermgr.cpp.s
.PHONY : BM/bm_buffermgr.cpp.s

BM/bm_hashTable.o: BM/bm_hashTable.cpp.o

.PHONY : BM/bm_hashTable.o

# target to build an object file
BM/bm_hashTable.cpp.o:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/BM/bm_hashTable.cpp.o
.PHONY : BM/bm_hashTable.cpp.o

BM/bm_hashTable.i: BM/bm_hashTable.cpp.i

.PHONY : BM/bm_hashTable.i

# target to preprocess a source file
BM/bm_hashTable.cpp.i:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/BM/bm_hashTable.cpp.i
.PHONY : BM/bm_hashTable.cpp.i

BM/bm_hashTable.s: BM/bm_hashTable.cpp.s

.PHONY : BM/bm_hashTable.s

# target to generate assembly for a file
BM/bm_hashTable.cpp.s:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/BM/bm_hashTable.cpp.s
.PHONY : BM/bm_hashTable.cpp.s

PF/pf_filemgr.o: PF/pf_filemgr.cpp.o

.PHONY : PF/pf_filemgr.o

# target to build an object file
PF/pf_filemgr.cpp.o:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/PF/pf_filemgr.cpp.o
.PHONY : PF/pf_filemgr.cpp.o

PF/pf_filemgr.i: PF/pf_filemgr.cpp.i

.PHONY : PF/pf_filemgr.i

# target to preprocess a source file
PF/pf_filemgr.cpp.i:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/PF/pf_filemgr.cpp.i
.PHONY : PF/pf_filemgr.cpp.i

PF/pf_filemgr.s: PF/pf_filemgr.cpp.s

.PHONY : PF/pf_filemgr.s

# target to generate assembly for a file
PF/pf_filemgr.cpp.s:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/PF/pf_filemgr.cpp.s
.PHONY : PF/pf_filemgr.cpp.s

RM/rm.o: RM/rm.cpp.o

.PHONY : RM/rm.o

# target to build an object file
RM/rm.cpp.o:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm.cpp.o
.PHONY : RM/rm.cpp.o

RM/rm.i: RM/rm.cpp.i

.PHONY : RM/rm.i

# target to preprocess a source file
RM/rm.cpp.i:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm.cpp.i
.PHONY : RM/rm.cpp.i

RM/rm.s: RM/rm.cpp.s

.PHONY : RM/rm.s

# target to generate assembly for a file
RM/rm.cpp.s:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm.cpp.s
.PHONY : RM/rm.cpp.s

RM/rm_fileHandler.o: RM/rm_fileHandler.cpp.o

.PHONY : RM/rm_fileHandler.o

# target to build an object file
RM/rm_fileHandler.cpp.o:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm_fileHandler.cpp.o
.PHONY : RM/rm_fileHandler.cpp.o

RM/rm_fileHandler.i: RM/rm_fileHandler.cpp.i

.PHONY : RM/rm_fileHandler.i

# target to preprocess a source file
RM/rm_fileHandler.cpp.i:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm_fileHandler.cpp.i
.PHONY : RM/rm_fileHandler.cpp.i

RM/rm_fileHandler.s: RM/rm_fileHandler.cpp.s

.PHONY : RM/rm_fileHandler.s

# target to generate assembly for a file
RM/rm_fileHandler.cpp.s:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm_fileHandler.cpp.s
.PHONY : RM/rm_fileHandler.cpp.s

RM/rm_pageHandler.o: RM/rm_pageHandler.cpp.o

.PHONY : RM/rm_pageHandler.o

# target to build an object file
RM/rm_pageHandler.cpp.o:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm_pageHandler.cpp.o
.PHONY : RM/rm_pageHandler.cpp.o

RM/rm_pageHandler.i: RM/rm_pageHandler.cpp.i

.PHONY : RM/rm_pageHandler.i

# target to preprocess a source file
RM/rm_pageHandler.cpp.i:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm_pageHandler.cpp.i
.PHONY : RM/rm_pageHandler.cpp.i

RM/rm_pageHandler.s: RM/rm_pageHandler.cpp.s

.PHONY : RM/rm_pageHandler.s

# target to generate assembly for a file
RM/rm_pageHandler.cpp.s:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm_pageHandler.cpp.s
.PHONY : RM/rm_pageHandler.cpp.s

RM/rm_test.o: RM/rm_test.cpp.o

.PHONY : RM/rm_test.o

# target to build an object file
RM/rm_test.cpp.o:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm_test.cpp.o
.PHONY : RM/rm_test.cpp.o

RM/rm_test.i: RM/rm_test.cpp.i

.PHONY : RM/rm_test.i

# target to preprocess a source file
RM/rm_test.cpp.i:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm_test.cpp.i
.PHONY : RM/rm_test.cpp.i

RM/rm_test.s: RM/rm_test.cpp.s

.PHONY : RM/rm_test.s

# target to generate assembly for a file
RM/rm_test.cpp.s:
	$(MAKE) -f CMakeFiles/miniSqlFrom0.dir/build.make CMakeFiles/miniSqlFrom0.dir/RM/rm_test.cpp.s
.PHONY : RM/rm_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... miniSqlFrom0"
	@echo "... BM/bm_buffermgr.o"
	@echo "... BM/bm_buffermgr.i"
	@echo "... BM/bm_buffermgr.s"
	@echo "... BM/bm_hashTable.o"
	@echo "... BM/bm_hashTable.i"
	@echo "... BM/bm_hashTable.s"
	@echo "... PF/pf_filemgr.o"
	@echo "... PF/pf_filemgr.i"
	@echo "... PF/pf_filemgr.s"
	@echo "... RM/rm.o"
	@echo "... RM/rm.i"
	@echo "... RM/rm.s"
	@echo "... RM/rm_fileHandler.o"
	@echo "... RM/rm_fileHandler.i"
	@echo "... RM/rm_fileHandler.s"
	@echo "... RM/rm_pageHandler.o"
	@echo "... RM/rm_pageHandler.i"
	@echo "... RM/rm_pageHandler.s"
	@echo "... RM/rm_test.o"
	@echo "... RM/rm_test.i"
	@echo "... RM/rm_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

